# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-10 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=256)),
                ('m_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('f_type', models.CharField(default='', max_length=128)),
            ],
            options={
                'verbose_name': '\u88ab\u76d1\u63a7\u6587\u4ef6',
                'verbose_name_plural': '\u88ab\u76d1\u63a7\u6587\u4ef6',
            },
        ),
    ]
